---
blank_issues_enabled: true
contact_links:
  - name: New Issue for X-WRT
    url: https://github.com/x-wrt/x-wrt/issues/new
    about: Post your Issue or your request.
  - name: X-WRT Blog
    url: https://blog.x-wrt.com/
    about: The X-WRT blog contains a lot of valuable information.
  - name: New Issue for OpenWrt
    url: https://github.com/openwrt/openwrt/issues
    about: Post your Issue to openwrt if you are sure it is an upstream issue.
