name: Build Toolchains

on:
  push:
    tags:
      - '_no_build_*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-toolchains:
    name: Build Toolchains for each target
    permissions:
      contents: read
      packages: read
      actions: write
    uses: openwrt/actions-shared-workflows/.github/workflows/toolchain.yml@main
