name: Build host tools

on:
  push:
    tags:
      - '_no_build_*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-tools:
    name: Build host tools for linux and macos based systems
    uses: openwrt/actions-shared-workflows/.github/workflows/tools.yml@main
